# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5c574aee5dd4c53b8d99b51dccff509c84b5499ad187d1a01344dd3af10d156ce9a085a41cf7e2499316b493d57887bd0a68236ffc75f1f35c003e036777fb65

test:
  secret_key_base: 8f468104320c87e8cc1ee9ee8b11b6c33fae5cf560d77c7cb79b6ce725956edfb8c8363b45f15146b0a8a886f4903616bcc6f5ff4a01cf0ec1f8d7322b1f68d2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
